name: PubMed Literature Summary to Email THA/TKA

on:
  schedule:
    - cron: '30 22 * * *' # Runs daily at 22:30 UTC (06:30 Beijing time)
  workflow_dispatch: # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download database (if exists)
        uses: actions/download-artifact@v4
        with:
          name: processed_articles_db
          path: . # Important: Download to the current working directory
        if: github.run_number > 1 # Skip on the first run

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Run script
        run: python Grok3_paper_research.py
        env:
          PUBMED_API_KEY: ${{ secrets.PUBMED_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
          SEARCH_QUERY: ${{ secrets.SEARCH_QUERY }}
          MAX_RESULTS: ${{ secrets.MAX_RESULTS }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SUMMARY_LANGUAGE: ${{ secrets.SUMMARY_LANGUAGE }}

      - name: Upload database (optional)
        uses: actions/upload-artifact@v4
        with:
          name: processed_articles_db
          path: processed_articles.db
