name: PubMed Literature Summary to Email THA/TKA

on:
  schedule:
    - cron: '30 22 * * *' # Runs daily at 22:30 UTC (06:30 Beijing time)
  workflow_dispatch: # Allows manual triggering

jobs:
  run_summarizer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for correct diffing

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Restore database
        run: |
          # Check if the database file exists in the repository
          if [ -f processed_articles.db ]; then
            echo "Database file found in the repository. Restoring..."
          else
            echo "Database file not found in the repository. Starting with a new database."
          fi
          # No action needed here. The presence of the file is sufficient.

      - name: Run summarizer script
        env:
          PUBMED_API_KEY: ${{ secrets.PUBMED_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
          SEARCH_QUERY: ${{ secrets.SEARCH_QUERY }}
          MAX_RESULTS: ${{ secrets.MAX_RESULTS }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SUMMARY_LANGUAGE: ${{ secrets.SUMMARY_LANGUAGE }}
        run: python Grok3_paper_research.py

      - name: Commit and push database
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions Bot"
          git add processed_articles.db
          git diff --quiet --exit-code || (git commit -m "Update processed_articles.db" && git push)
