name: PubMed Literature Summary to Email THA/TKA

on:
  schedule:
    - cron: '30 22 * * *' # Runs daily at 22:30 UTC (06:30 Beijing time)
  workflow_dispatch: # Allows manual triggering  Grok3_paper_research.py
  
# 添加权限块
permissions:
  actions: read
  contents: read
  # 如果需要上传 artifact 到其他仓库，可能需要 write 权限
  # contents: write

jobs:
  run_summarizer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Download database artifact
        id: download_db
        uses: actions/download-artifact@v3
        with:
          name: processed-articles-db
          path: ./
        continue-on-error: true
        # 添加 token
        # token: ${{ secrets.GITHUB_TOKEN }}  # 尝试显式提供 token

      - name: Check if database exists
        id: check_db
        run: |
          if [ -f processed_articles.db ] && [ "${{ steps.download_db.outcome }}" == "success" ]; then
            echo "Database file found from artifact. Restoring..."
            echo "DB_EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "Database file not found or download failed. Starting with a new database."
            echo "DB_EXISTS=false" >> $GITHUB_OUTPUT
          fi

      - name: Run summarizer script
        env:
          PUBMED_API_KEY: ${{ secrets.PUBMED_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
          SEARCH_QUERY: ${{ secrets.SEARCH_QUERY }}
          MAX_RESULTS: ${{ secrets.MAX_RESULTS }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SUMMARY_LANGUAGE: ${{ secrets.SUMMARY_LANGUAGE }}
        run: python Grok3_paper_research.py

      - name: Upload database artifact
        uses: actions/upload-artifact@v3
        with:
          name: processed-articles-db
          path: processed_articles.db
          if-version-control: false
