name: PubMed Literature Summary to Email THA/TKA

on:
  schedule:
    - cron: '30 22 * * *' # Runs daily at 22:30 UTC (06:30 Beijing time)
  workflow_dispatch: # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check database file before run
        run: |
          ls -lh processed_articles.db || echo "No database file exists yet"

      - name: Run PubMed Summary Script
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          PUBMED_API_KEY: ${{ secrets.PUBMED_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SEARCH_QUERY: ${{ secrets.SEARCH_QUERY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python Grok3_paper_research.py

      - name: Check database file after run
        run: |
          ls -lh processed_articles.db || echo "Database file not found after script run"

      - name: Commit and push database
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add processed_articles.db
          git commit -m "Update processed_articles.db with latest run" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
