name: PubMed Literature Summary to Email THA/TKA

on:
  schedule:
    - cron: '30 22 * * *' # Runs daily at 22:30 UTC (06:30 Beijing time)
  workflow_dispatch: # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download previous database
        uses: actions/download-artifact@v4
        with:
          name: processed_articles_db
          path: .
        continue-on-error: true

      - name: Check downloaded file
        run: |
          ls -lh processed_articles.db || echo "No database file downloaded"

      - name: Run PubMed Summary Script
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          PUBMED_API_KEY: ${{ secrets.PUBMED_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SEARCH_QUERY: ${{ secrets.SEARCH_QUERY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python Grok3_paper_research.py

      - name: Check database file
        run: |
          ls -lh processed_articles.db || echo "Database file not found"

      - name: Upload database as artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed_articles_db
          path: processed_articles.db
