name: PubMed Literature Summary to Email THA/TKA

on:
  schedule:
    - cron: '30 22 * * *' # Runs daily at 22:30 UTC (06:30 Beijing time)
  workflow_dispatch: # Allows manual triggering  Grok3_paper_research.py
  

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Set environment variables
        run: |
          echo "PUBMED_API_KEY=${{ secrets.PUBMED_API_KEY }}" >> $GITHUB_ENV
          echo "EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "EMAIL_SMTP_SERVER=${{ secrets.EMAIL_SMTP_SERVER }}" >> $GITHUB_ENV
          echo "EMAIL_SMTP_PORT=${{ secrets.EMAIL_SMTP_PORT }}" >> $GITHUB_ENV
          echo "SEARCH_QUERY=${{ secrets.SEARCH_QUERY }}" >> $GITHUB_ENV
          echo "MAX_RESULTS=${{ secrets.MAX_RESULTS }}" >> $GITHUB_ENV
          echo "XAI_API_KEY=${{ secrets.XAI_API_KEY }}" >> $GITHUB_ENV
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV
          echo "SUMMARY_LANGUAGE=${{ secrets.SUMMARY_LANGUAGE }}" >> $GITHUB_ENV

      - name: Run script
        run: python Grok3_paper_research.py # Replace your_script_name.py with the actual name of your python file
        env:
          PUBMED_API_KEY: ${{ secrets.PUBMED_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
          SEARCH_QUERY: ${{ secrets.SEARCH_QUERY }}
          MAX_RESULTS: ${{ secrets.MAX_RESULTS }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SUMMARY_LANGUAGE: ${{ secrets.SUMMARY_LANGUAGE }}

      - name: Upload database (optional)
        uses: actions/upload-artifact@v4
        with:
          name: processed_articles_db
          path: processed_articles.db
          if-no-files-found: error # Ensure artifact is uploaded even if no changes
