name: PubMed Literature Summary to Email

on:
  schedule:
    - cron: '30 22 * * *'  # 每天 UTC 22:30 运行（北京时间 06:30）
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch_summarize_and_send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests lxml openai biopython google-generativeai beautifulsoup4 python-dotenv

      - name: Cache processed articles
        uses: actions/cache@v3
        with:
          path: processed_articles.json
          key: processed-articles-${{ hashFiles('processed_articles.json') }}

      - name: Fetch, Summarize and Send Email
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
          SEARCH_QUERY: ${{ secrets.SEARCH_QUERY }}
          PUBMED_API_KEY: ${{ secrets.PUBMED_API_KEY }}
          MAX_RESULTS: ${{ secrets.MAX_RESULTS }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python WX_send_Email.py
